version: '3'
services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
    - "celery"

  celery:
    build: .
    command: celery -A tasks worker --loglevel=INFO
    depends_on:
      - "redis"

  redis:
    image: redis
